backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "sliders"
    label: "Sliders"
    folder: "content/sliders"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "subtitle", label: "Subtitle", widget: "string" }
      - { name: "link", label: "Link", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
