backend:
  name: github
  repo: MulweliMX/VTYGaming
  branch: main  # Correct indentation here
  identity: true





media_folder: "VUTOMYTRUCKING/assets/images"
public_folder: "/assets/images"

collections:
  - name: "slider-items"
    label: "Slider Items"
    folder: "VUTOMYTRUCKING/slider-items"
    create: true
    slug: "{{slug}}"
    media_folder: "VUTOMYTRUCKING/assets/images"
    public_folder: "/assets/images"

    fields:
      - { name: "link", label: "Link", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "subtitle", label: "Subtitle", widget: "string" }
